// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE, Channel } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	/**
	 *  Манифест всех версий Minecraft. `refresh` зарезервирован под
	 *  серверный кэш (сейчас кэширование — на стороне фронтенда, TanStack
	 *  Query), поэтому пока просто игнорируется.
	 */
	versionsManifest: (refresh: boolean) => typedError<VersionManifestDto, DreamError>(__TAURI_INVOKE("versions_manifest", { refresh })),
	accountsList: () => typedError<AccountDto[], DreamError>(__TAURI_INVOKE("accounts_list")),
	/**
	 *  Добавляет офлайн-профиль: имя + детерминированный UUID, без сети.
	 *  Первый добавленный аккаунт автоматически становится активным.
	 */
	accountAddOffline: (name: string) => typedError<AccountDto, DreamError>(__TAURI_INVOKE("account_add_offline", { name })),
	/**
	 *  Добавляет Microsoft-аккаунт через Device Code Flow. `client_id` берётся
	 *  из настроек приложения (регистрация Azure-приложения). Прогресс идёт
	 *  через `Channel` — UI показывает код и ссылку для авторизации.
	 */
	accountAddMicrosoft: (progress: Channel<AuthProgressDto>) => typedError<AccountDto, DreamError>(__TAURI_INVOKE("account_add_microsoft", { progress })),
	/**
	 *  Обновляет истёкший access token Microsoft-аккаунта через refresh token.
	 *  Автоматически вызывается при запуске инстанса, если токен протух.
	 */
	accountRefreshMicrosoft: (accountId: string) => typedError<null, DreamError>(__TAURI_INVOKE("account_refresh_microsoft", { accountId })),
	accountSetActive: (id: string) => typedError<null, DreamError>(__TAURI_INVOKE("account_set_active", { id })),
	accountRemove: (id: string) => typedError<null, DreamError>(__TAURI_INVOKE("account_remove", { id })),
	instancesList: () => typedError<InstanceDto[], DreamError>(__TAURI_INVOKE("instances_list")),
	instanceCreate: (req: CreateInstanceRequest) => typedError<InstanceDto, DreamError>(__TAURI_INVOKE("instance_create", { req })),
	/**
	 *  RAM и дополнительные JVM-аргументы — версия игры/загрузчик не
	 *  редактируются намеренно (см. `UpdateInstanceRequest`).
	 */
	instanceUpdate: (req: UpdateInstanceRequest) => typedError<InstanceDto, DreamError>(__TAURI_INVOKE("instance_update", { req })),
	/**  Открывает папку игры (`.minecraft`) инстанса в проводнике. */
	instanceOpenFolder: (id: string) => typedError<null, DreamError>(__TAURI_INVOKE("instance_open_folder", { id })),
	instanceDelete: (id: string) => typedError<null, DreamError>(__TAURI_INVOKE("instance_delete", { id })),
	/**  Версии загрузчика для конкретной версии Minecraft, самые новые первыми. */
	loaderVersions: (loader: string, mcVersion: string) => typedError<string[], DreamError>(__TAURI_INVOKE("loader_versions", { loader, mcVersion })),
	/**
	 *  Скачивает и раскладывает на диск всё, что нужно для запуска инстанса:
	 *  client.jar, библиотеки, натив-либы, ассеты и (при необходимости) Java.
	 *  Идемпотентна — уже валидные файлы просто пропускаются, поэтому её
	 *  безопасно вызывать перед каждым запуском игры.
	 */
	installVersion: (instanceId: string, channel: Channel<InstallProgressEvent>) => typedError<null, DreamError>(__TAURI_INVOKE("install_version", { instanceId, channel })),
	/**
	 *  Запускает уже установленную (см. `install_version`) версию. Не
	 *  проверяет повторно наличие файлов на диске — если что-то отсутствует,
	 *  Java просто упадёт с понятной ошибкой в stderr, который уходит в канал.
	 */
	launchInstance: (instanceId: string, channel: Channel<LaunchEventDto>) => typedError<null, DreamError>(__TAURI_INVOKE("launch_instance", { instanceId, channel })),
	/**  Поиск модов, уже отфильтрованный под версию игры и загрузчик инстанса. */
	modsSearch: (instanceId: string, query: string, offset: number) => typedError<ModSearchResultDto, DreamError>(__TAURI_INVOKE("mods_search", { instanceId, query, offset })),
	modsList: (instanceId: string) => typedError<InstalledModDto[], DreamError>(__TAURI_INVOKE("mods_list", { instanceId })),
	modsInstall: (instanceId: string, projectId: string) => typedError<string[], DreamError>(__TAURI_INVOKE("mods_install", { instanceId, projectId })),
	/**
	 *  Выключенные моды переименовываются в `<файл>.disabled` — Minecraft
	 *  такие просто не подхватывает, без удаления с диска.
	 */
	modsToggle: (instanceId: string, projectId: string) => typedError<null, DreamError>(__TAURI_INVOKE("mods_toggle", { instanceId, projectId })),
	modsRemove: (instanceId: string, projectId: string) => typedError<null, DreamError>(__TAURI_INVOKE("mods_remove", { instanceId, projectId })),
	/**  Поиск шейдер-паков для версии игры инстанса. */
	shadersSearch: (instanceId: string, query: string, offset: number) => typedError<ShaderSearchResultDto, DreamError>(__TAURI_INVOKE("shaders_search", { instanceId, query, offset })),
	shadersList: (instanceId: string) => typedError<InstalledShaderDto[], DreamError>(__TAURI_INVOKE("shaders_list", { instanceId })),
	/**  Устанавливает шейдер-пак. Автоматически проверяет наличие Iris/OptiFine. */
	shadersInstall: (instanceId: string, projectId: string) => typedError<string, DreamError>(__TAURI_INVOKE("shaders_install", { instanceId, projectId })),
	/**  Устанавливает активный шейдер (None = отключить шейдеры). */
	shadersSetActive: (instanceId: string, projectId: string | null) => typedError<null, DreamError>(__TAURI_INVOKE("shaders_set_active", { instanceId, projectId })),
	shadersRemove: (instanceId: string, projectId: string) => typedError<null, DreamError>(__TAURI_INVOKE("shaders_remove", { instanceId, projectId })),
	/**  Ищет свежие крэш-репорты для инстанса (до 5 штук). */
	crashesList: (instanceId: string) => typedError<CrashReportDto[], DreamError>(__TAURI_INVOKE("crashes_list", { instanceId })),
	/**  Читает полное содержимое крэш-репорта по пути. */
	crashRead: (path: string) => typedError<string, DreamError>(__TAURI_INVOKE("crash_read", { path })),
};

/* Types */
export type AccountDto = {
	id: string,
	username: string,
	kind: string,
	is_active: boolean,
};

/**  Прогресс Microsoft OAuth авторизации — отправляется через Channel. */
export type AuthProgressDto = { type: "WaitingForUser"; user_code: string; verification_uri: string; expires_in: number } | { type: "Polling" } | { type: "ExchangingXboxLive" } | { type: "ExchangingXsts" } | { type: "LoggingIntoMinecraft" } | { type: "FetchingProfile" } | { type: "Complete"; uuid: string; username: string } | { type: "Error"; message: string };

/**  Крэш-репорт Minecraft. */
export type CrashReportDto = {
	path: string,
	kind: string,
	preview: string,
	modified: number,
};

export type CreateInstanceRequest = {
	name: string,
	mc_version: string,
	loader: string,
	/**  Обязателен для fabric/quilt, игнорируется для vanilla. */
	loader_version: string | null,
};

export type DreamError = { kind: "Core"; message: string } | { kind: "Io"; message: string } | { kind: "Other"; message: string };

/**
 *  Прогресс установки версии — один канал на весь процесс: скачивание
 *  метаданных, файлов, распаковка натив-либ и (для старых версий)
 *  раскладка ассетов.
 */
export type InstallProgressEvent = { type: "Phase"; message: string } | 
/**
 *  `done`/`total` считаются по файлам (не по байтам) — событие
 *  приходит на каждый обработанный файл.
 */
{ type: "Progress"; done: number; total: number } | { type: "ItemFailed"; url: string; error: string } | { type: "Done" } | { type: "Error"; message: string };

export type InstalledModDto = {
	project_id: string,
	version_id: string,
	filename: string,
	enabled: boolean,
};

export type InstalledShaderDto = {
	project_id: string,
	version_id: string,
	filename: string,
	is_active: boolean,
};

export type InstanceDto = {
	id: string,
	slug: string,
	name: string,
	mc_version: string,
	loader: string,
	loader_version: string | null,
	min_ram_mb: number,
	max_ram_mb: number,
	extra_jvm_args: string,
};

export type LatestVersionsDto = {
	release: string,
	snapshot: string,
};

/**  События запущенного процесса игры. */
export type LaunchEventDto = { type: "Starting" } | { type: "Stdout"; line: string } | { type: "Stderr"; line: string } | { type: "Exited"; code: number | null } | { type: "Error"; message: string };

export type ModSearchHitDto = {
	project_id: string,
	slug: string,
	title: string,
	description: string,
	author: string,
	downloads: number,
	icon_url: string | null,
};

export type ModSearchResultDto = {
	hits: ModSearchHitDto[],
	total_hits: number,
};

export type ShaderSearchResultDto = {
	hits: ModSearchHitDto[],
	total_hits: number,
};

/**
 *  Изменяемые поля инстанса — RAM и дополнительные JVM-аргументы. Версия
 *  игры/загрузчик намеренно не редактируются (это фактически новый
 *  инстанс — проще пересоздать, чем мигрировать установленные файлы).
 */
export type UpdateInstanceRequest = {
	id: string,
	min_ram_mb: number,
	max_ram_mb: number,
	extra_jvm_args: string,
};

export type VersionEntryDto = {
	id: string,
	kind: string,
	release_time: string,
};

export type VersionManifestDto = {
	latest: LatestVersionsDto,
	versions: VersionEntryDto[],
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

